//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExternalService.AccomodationServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccomodationServiceReference.IAccomodationService")]
    public interface IAccomodationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccomodationService/ReceiveInvoice", ReplyAction="http://tempuri.org/IAccomodationService/ReceiveInvoiceResponse")]
        void ReceiveInvoice(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccomodationService/ReceiveInvoice", ReplyAction="http://tempuri.org/IAccomodationService/ReceiveInvoiceResponse")]
        System.Threading.Tasks.Task ReceiveInvoiceAsync(string json);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccomodationServiceChannel : ExternalService.AccomodationServiceReference.IAccomodationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccomodationServiceClient : System.ServiceModel.ClientBase<ExternalService.AccomodationServiceReference.IAccomodationService>, ExternalService.AccomodationServiceReference.IAccomodationService {
        
        public AccomodationServiceClient() {
        }
        
        public AccomodationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccomodationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccomodationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccomodationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ReceiveInvoice(string json) {
            base.Channel.ReceiveInvoice(json);
        }
        
        public System.Threading.Tasks.Task ReceiveInvoiceAsync(string json) {
            return base.Channel.ReceiveInvoiceAsync(json);
        }
    }
}
